name       : python-cachetools
version    : 3.1.1
release    : 1
source     :
    - https://files.pythonhosted.org/packages/ae/37/7fd45996b19200e0cb2027a0b6bef4636951c4ea111bfad36c71287247f6/cachetools-3.1.1.tar.gz : 8ea2d3ce97850f31e4a08b0e2b5e6c34997d7216a9d2c98e0f3978630d4da69a
license    : MIT
component  : programming.python
summary    : Extensible memoizing collections and decorators
description: |
    This module provides various memoizing collections and decorators, including variants of the Python 3 Standard Library @lru_cache function decorator.
rundeps    :
    - python3
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
