name       : python-cachetools
version    : 5.3.1
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/c/cachetools/cachetools-5.3.1.tar.gz : dce83f2d9b4e1f732a8cd44af8e8fab2dbe46201467fc98b3ef8f269092bf62b
homepage   : https://github.com/tkem/cachetools/
license    : MIT
component  : programming.python
summary    : Extensible memoizing collections and decorators
description: |
    This module provides various memoizing collections and decorators, including variants of the Python 3 Standard Library @lru_cache function decorator.
rundeps    :
    - python3
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
